// <auto-generated />
using System;
using ClinicaSaludAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaSaludAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClinicaSaludAPI.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("HoraCita")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCita");

                    b.HasIndex("IdMedico");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("ClinicaSaludAPI.Models.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            IdEspecialidad = 1,
                            Descripcion = "Atención primaria y consultas generales para toda la familia.",
                            NombreEspecialidad = "Medicina General"
                        },
                        new
                        {
                            IdEspecialidad = 2,
                            Descripcion = "Cuidado especializado para bebés, niños y adolescentes.",
                            NombreEspecialidad = "Pediatría"
                        },
                        new
                        {
                            IdEspecialidad = 3,
                            Descripcion = "Salud oral, limpiezas, tratamientos y estética dental.",
                            NombreEspecialidad = "Odontología"
                        },
                        new
                        {
                            IdEspecialidad = 4,
                            Descripcion = "Diagnóstico y tratamiento de enfermedades del corazón.",
                            NombreEspecialidad = "Cardiología"
                        },
                        new
                        {
                            IdEspecialidad = 5,
                            Descripcion = "Salud femenina, control prenatal y seguimiento especializado.",
                            NombreEspecialidad = "Ginecología"
                        },
                        new
                        {
                            IdEspecialidad = 6,
                            Descripcion = "Lesiones musculares, articulaciones y rehabilitación.",
                            NombreEspecialidad = "Traumatología"
                        });
                });

            modelBuilder.Entity("ClinicaSaludAPI.Models.Medico", b =>
                {
                    b.Property<int>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMedico"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoMedico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HorarioAtencion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdMedico");

                    b.HasIndex("CodigoMedico")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            IdMedico = 1,
                            Activo = true,
                            CodigoMedico = "MG-001",
                            Estado = "disponible",
                            HorarioAtencion = "Lun–Vie 8am–4pm",
                            IdEspecialidad = 1,
                            NombreCompleto = "Dr. Andrés Gómez"
                        },
                        new
                        {
                            IdMedico = 2,
                            Activo = true,
                            CodigoMedico = "MG-002",
                            Estado = "disponible",
                            HorarioAtencion = "Lun–Sáb 9am–5pm",
                            IdEspecialidad = 1,
                            NombreCompleto = "Dra. Laura Herrera"
                        },
                        new
                        {
                            IdMedico = 3,
                            Activo = true,
                            CodigoMedico = "PD-001",
                            Estado = "disponible",
                            HorarioAtencion = "Lun–Vie 7am–3pm",
                            IdEspecialidad = 2,
                            NombreCompleto = "Dra. Sofía Ramírez"
                        },
                        new
                        {
                            IdMedico = 4,
                            Activo = true,
                            CodigoMedico = "PD-002",
                            Estado = "ocupado",
                            HorarioAtencion = "Mar–Sáb 10am–6pm",
                            IdEspecialidad = 2,
                            NombreCompleto = "Dr. Carlos Medina"
                        },
                        new
                        {
                            IdMedico = 5,
                            Activo = true,
                            CodigoMedico = "OD-001",
                            Estado = "disponible",
                            HorarioAtencion = "Lun–Vie 8am–5pm",
                            IdEspecialidad = 3,
                            NombreCompleto = "Dr. Felipe Torres"
                        },
                        new
                        {
                            IdMedico = 6,
                            Activo = true,
                            CodigoMedico = "OD-002",
                            Estado = "disponible",
                            HorarioAtencion = "Lun–Sáb 9am–4pm",
                            IdEspecialidad = 3,
                            NombreCompleto = "Dra. Valentina Cruz"
                        },
                        new
                        {
                            IdMedico = 7,
                            Activo = true,
                            CodigoMedico = "CD-001",
                            Estado = "disponible",
                            HorarioAtencion = "Lun–Jue 8am–4pm",
                            IdEspecialidad = 4,
                            NombreCompleto = "Dr. Roberto Nieto"
                        },
                        new
                        {
                            IdMedico = 8,
                            Activo = true,
                            CodigoMedico = "CD-002",
                            Estado = "disponible",
                            HorarioAtencion = "Mié–Sáb 9am–5pm",
                            IdEspecialidad = 4,
                            NombreCompleto = "Dra. Marcela Ríos"
                        },
                        new
                        {
                            IdMedico = 9,
                            Activo = true,
                            CodigoMedico = "GN-001",
                            Estado = "disponible",
                            HorarioAtencion = "Lun–Vie 7am–3pm",
                            IdEspecialidad = 5,
                            NombreCompleto = "Dra. Patricia Lozano"
                        },
                        new
                        {
                            IdMedico = 10,
                            Activo = true,
                            CodigoMedico = "GN-002",
                            Estado = "ocupado",
                            HorarioAtencion = "Mar–Sáb 10am–6pm",
                            IdEspecialidad = 5,
                            NombreCompleto = "Dra. Isabel Morales"
                        },
                        new
                        {
                            IdMedico = 11,
                            Activo = true,
                            CodigoMedico = "TR-001",
                            Estado = "disponible",
                            HorarioAtencion = "Lun–Vie 8am–4pm",
                            IdEspecialidad = 6,
                            NombreCompleto = "Dr. Javier Pedraza"
                        },
                        new
                        {
                            IdMedico = 12,
                            Activo = true,
                            CodigoMedico = "TR-002",
                            Estado = "disponible",
                            HorarioAtencion = "Lun–Sáb 9am–5pm",
                            IdEspecialidad = 6,
                            NombreCompleto = "Dr. Santiago Vargas"
                        });
                });

            modelBuilder.Entity("ClinicaSaludAPI.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("EPS")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdPaciente");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaSaludAPI.Models.Recomendacion", b =>
                {
                    b.Property<int>("IdRecomendacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRecomendacion"));

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProximaCita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecomendacionesCuidados")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdRecomendacion");

                    b.HasIndex("IdCita")
                        .IsUnique();

                    b.ToTable("Recomendaciones");
                });

            modelBuilder.Entity("ClinicaSaludAPI.Models.Cita", b =>
                {
                    b.HasOne("ClinicaSaludAPI.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaSaludAPI.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaSaludAPI.Models.Medico", b =>
                {
                    b.HasOne("ClinicaSaludAPI.Models.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("ClinicaSaludAPI.Models.Recomendacion", b =>
                {
                    b.HasOne("ClinicaSaludAPI.Models.Cita", "Cita")
                        .WithOne()
                        .HasForeignKey("ClinicaSaludAPI.Models.Recomendacion", "IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });
#pragma warning restore 612, 618
        }
    }
}
